progenitor(maria,jose).
progenitor(joao,jose).
progenitor(joao,ana).
progenitor(jose,julia).
progenitor(jose,iris).
progenitor(iris,jorge).
masculino(joao).
masculino(ana).
masculino(jorge).
feminino(jose).
feminino(maria).
feminino(julia).
filho(X,Y):-progenitor(Y,X),masculino(X).
filha(X,Y):-progenitor(Y,X),feminino(X).
mae(X,Y):-progenitor(X,Y),feminino(X).
pai(X,Y):-progenitor(X,Y),masculino(X).
avow(X,Y):-masculino(X),progenitor(X,Z),progenitor(Z,Y).
avoh(X,Y):-feminino(X),progenitor(X,Z),progenitor(Z,Y).
irma(X,Y):-feminino(X),progenitor(Z,X),progenitor(Z,Y),X\=Y.
irmao(X,Y):-masculino(X),progenitor(Z,X),progenitor(Z,Y),X\=Y.
antepassado(X,Z):-progenitor(X,Z).
antepassado(X,Z):-progenitor(X,Y),antepassado(Y,Z).
